version: '3.9'

services:
  codeforces_app:
    restart: always
    build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8000:8000"
    links:
      - postgres
      # - redis
    volumes:
      - codeforces_app-django:/usr/src/app
      - codeforces_app-static:/usr/src/app/static
      # - /usr/src/app
      # - /usr/src/app/static
      #- ./app:/app
    env_file: ./codeforces_app/.env
    environment:
      - DEBUG='true'
      # The environment variable credentials that is needed 
      # in django settings for Postgres to work.
      - POSTGRES_HOST=postgres
      - POSTGRES_NAMEbf3e694f6345
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    command: /usr/local/bin/gunicorn codeforces_app.wsgi:application -w 2 -b :8000 --reload

  postgres:
    restart: always
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      # The environment variable credentials that is needed 
      # in django settings for Postgres to work.
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    expose:
          - 5432

  # redis:
  #       restart: unless-stopped
  #       image: redis:7.0.5-alpine 
  #       expose:
  #           - 6379

  # Celery worker
  # celery_worker:
  #   restart: unless-stopped
  #   build:
  #           context: .
  #           dockerfile: ./docker/backend/Dockerfile
  #   entrypoint: ./docker/backend/worker-entrypoint.sh
  #   volumes:
  #       - codeforces_app-static:/usr/src/app/static
  #   environment:
  #       - DEBUG="True"
  #       - CELERY_BROKER_URL="redis://redis:6379/0"
  #       - CELERY_RESULT_BACKEND="redis://redis:6379/0"
  #       - DJANGO_DB=postgresql
  #       - POSTGRES_HOST=postgres
  #       - POSTGRES_NAME
  #       - POSTGRES_USER
  #       - POSTGRES_PASSWORD
  #       - POSTGRES_PORT=5432
  #   depends_on:
  #       - codeforces_app
  #       - redis

volumes:
  codeforces_app-django:
  codeforces_app-static:
  #app:
  pgdata:
