# Generated by Django 4.1.7 on 2023-03-13 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_rename_contestid_problem_contest_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="points",
            field=models.FloatField(
                null=True, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
    ]
