# Generated by Django 4.1.7 on 2023-03-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_problem_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="tags",
        ),
        migrations.AddField(
            model_name="tag",
            name="problems",
            field=models.ManyToManyField(
                related_name="problems", to="main_app.problem"
            ),
        ),
    ]
