# Generated by Django 4.1.7 on 2023-03-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_remove_problem_tags_tag_problems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="problems",
        ),
        migrations.AddField(
            model_name="problem",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="main_app.tag"),
        ),
    ]
