# Generated by Django 4.1.7 on 2023-03-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_remove_tag_problems_problem_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
