# Generated by Django 4.1.7 on 2023-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="tags",
            field=models.ManyToManyField(to="main_app.tag"),
        ),
    ]
