# Generated by Django 4.1.7 on 2023-03-14 14:09

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_alter_problem_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="main_app.tag"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="type",
            field=models.CharField(
                choices=[
                    (main_app.models.TypeEnum["PROGRAMMING"], "PROGRAMMING"),
                    (main_app.models.TypeEnum["QUESTION"], "QUESTION"),
                ],
                max_length=200,
            ),
        ),
    ]
